name: Build Android APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code from Repository
      uses: actions/checkout@v4

    - name: Generate Cache Timestamp
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer Global Cache
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Install Android Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev xclip libsdl2-dev libsdl2-image-dev libsdl2-txt-dev libsdl2-ttf-dev make fontconfig libjpeg-dev autoconf automake libtool pkg-config zlib1g-dev python3-pip python3-setuptools
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Compile APK via Buildozer Cloud Engine
      run: |
        export PATH=$PATH:~/.local/bin
        yes | buildozer -v android debug

    - name: Export Verified Production APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Keep-Secret-VIP-v5.6-APK
        path: bin/*.apk
        
